### ISSUE TITLE
Missing menu folder

### ISSUE THREAD

**Issue by lordskyzw** [nilesh-kawar/Online-Food-Ordering-System#4]
The menu folder containing menu.php is missing.

**Comment by nilesh-kawar** [comment]
Yes, Because the project is no longer available for free. If you want full
working source code then let me know.

**Comment by lordskyzw** [comment]
I’d like a full working source code

**Comment by nilesh-kawar** [comment]
Project is for sale. If you want to buy the project please let me know,
price is very less.
You can text me on my telegram ID: https://t.me/nilesh_kawar
Thank you
